apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: 0311at-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      initContainers:
      - name: copy-content
        image: busybox
        command: ['sh', '-c', 'until [ -d /mnt/website ]; do sleep 2; done; cp -r /mnt/website/* /usr/share/nginx/html']
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: host-volume
          mountPath: /mnt/website
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        envFrom:
        - configMapRef:
            name: 0311at-config
      volumes:
      - name: html-volume
        emptyDir: {}
      - name: host-volume
        persistentVolumeClaim:
          claimName: 0311at-pvc-html