apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: 0311at-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        envFrom:
        - configMapRef:
            name: 0311at-config
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: 0311at-pvc-html