apiVersion: v1
kind: PersistentVolume
metadata:
  name: 0311at-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/website"  # Ruta que montaremos con minikube mount
    type: Directory
