apiVersion: v1
kind: PersistentVolume
metadata:
  name: 0311at-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/website"
    type: DirectoryOrCreate